backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "posting" # Used in routes, e.g., /admin/collections/blog
    label: "Posting" # Used in the UI
    folder: "src/postings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter.
    # Remove any that aren't needed for posts
      - {label: "Name", name: "name", widget: 'text'}
      - {label: "Phone Number", name: "phone", widget: 'text'}
      - {label: "Additional Description", name: "description", widget: 'markdown', required: false}
